# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 # Port for app1
      name: app1-port
    - protocol: TCP
      port: 5001
      targetPort: 5001 # Port for app2
      name: app2-port
  type: LoadBalancer